In [13]:
#Mnożenie
import numpy as np

A=np.array([[5,6,7],[2,4,6]])
print(A)

B=np.array([[5,5],[6,6],[2,3]])
print(B)

C=np.dot(A,B)
C

[[5 6 7]
 [2 4 6]]
[[5 5]
 [6 6]
 [2 3]]


array([[75, 82],
       [46, 52]])

In [17]:
#napisz macierzowo i rozwiąż układ równań
import numpy as np

A = np.array([[2,3,5],[4,-2,-7],[9,5,-3]])
B = np.array([1,8,2])

solution = np.linalg.solve(A,B)
solution


array([ 2.44537815, -3.28571429,  1.19327731])

In [18]:
import numpy as np
#zadania PWr W.Dudek
#1
A=np.transpose([[1,1,1],[1,0,2]])
B=np.array([[1,2,3],[0,1,2]])
C=np.dot(A,B)
print(C)
#2  (B^T A)^2
D=np.array([[1,1,2],[0,2,-1]])
E=np.array([[2,3,1],[2,1,0]])
F=np.linalg.matrix_power(np.dot(np.transpose(D),E),2)
print(F)
G=np.array([[0,-1,1],[2,1,-2]])
H=np.dot(np.transpose(G),G)-np.dot(4,np.eye(3))
print(H)
#wyznaczniki zad1
J=np.array([[1,1,1],[1,2,3],[2,5,6]])
detJ=np.linalg.det(J)
print(f'wyznacznik{detJ}')
#rozwiniecie laplace
K=np.array([[0,4,0,2,0,1],[5,0,1,2,0,6],[4,3,2,1,1,0],[2,0,1,1,0,0],[0,2,0,0,3,0],[0,1,0,0,6,0]])
detK=np.linalg.det(K)
print(detK)

[[1 3 5]
 [1 2 3]
 [1 4 7]]
[[24 26  7]
 [44 48 13]
 [38 41 11]]
[[ 0.  2. -4.]
 [ 2. -2. -3.]
 [-4. -3.  1.]]
wyznacznik-1.9999999999999993
-27.0


In [ ]:
#układy rownan przez sympy
#W pewnym kurniku mieszkaja kury i szczury. Razem maja one 35 glow i 94 nogi. Ile jest kur, a ile szczurow?

