In [13]:
#Mnożenie
import numpy as np

A=np.array([[5,6,7],[2,4,6]])
print(A)

B=np.array([[5,5],[6,6],[2,3]])
print(B)

C=np.dot(A,B)
C

[[5 6 7]
 [2 4 6]]
[[5 5]
 [6 6]
 [2 3]]


array([[75, 82],
       [46, 52]])

In [17]:
#napisz macierzowo i rozwiąż układ równań
import numpy as np

A = np.array([[2,3,5],[4,-2,-7],[9,5,-3]])
B = np.array([1,8,2])

solution = np.linalg.solve(A,B)
solution


array([ 2.44537815, -3.28571429,  1.19327731])