Dział 4. Rozkład macierzy

In [ ]:
#funkcje z tego rozdziału:
#forma zapisu macierzy macierz = np.array([[2, 2, 3], [4, 5, 6], [7, 8, 9]])
#     detA= np.linalg.det(macierz)   -wyznacznik
#     odwrotnaMacierz = np.linalg.inv(macierz)    -odwrócona macierz
#     ślad macierzy = np.trace(macierz))


In [29]:
import numpy as np
#ad 1. odwrotność macierzy

#funkcja:  cc = np.linalg.inv(macierz)
macierz = np.array([[2, 2, 3], [4, 5, 6], [7, 8, 9]])
print(macierz)

# Wyznacznik
detA= np.linalg.det(macierz)
print(f'Wyznacznik: {detA}')

#odwrotność
odwrotnaMacierz = np.linalg.inv(macierz)
print(odwrotnaMacierz)
#Macierz odwracalna (wyzn rozny od zera)(macierz nieosobliwa) = brak ukrytych zależności między kolumnami i wierszami

#ślad
slad = np.trace(macierz)
print(f'ślad: {slad}')


[[2 2 3]
 [4 5 6]
 [7 8 9]]
Wyznacznik: -3.0000000000000018
[[ 1.         -2.          1.        ]
 [-2.          1.          0.        ]
 [ 1.          0.66666667 -0.66666667]]
ślad: 16


4.1 Wyznacznik   
Tylko dla macierzy kwadratowych.
Co mówi wyznacznik
- Czy macierz jest odwracalna (czyli czy istnieje macierz odwrotna) 
- Czy układ równań liniowych ma jednoznaczne rozwiązanie $\text{det}(A) \neq 0$. 
- Jakie zmiany zachodzą w objętości i orientacji przestrzeni po przekształceniu liniowym.
-nieopisane Czy kolumny (lub wiersze) macierzy są liniowo niezależne.
-nieopisane Objawia stabilność układów numerycznych i analiz geometrycznych.

Ad5. W analizie numerycznej wyznacznik może mieć znaczenie przy badaniu stabilności obliczeń. Układy z wyznacznikiem bliskim zera mogą być niestabilne, ponieważ macierz jest bliska bycia osobliwą, co oznacza, że nawet małe zmiany w danych wejściowych mogą prowadzić do dużych zmian w wynikach.

4.1.1 odwrotność macierzy

$A \cdot A^{-1} = A^{-1} \cdot A = I$    
I to macierz jednostkowa, elementy na glownej przekątnej =1 

Jeżeli istnieje odwrotność, czyli $\text{det}(A) \neq 0$ 

to brak ukrytych zależności między kolumnami i wierszami.

oraz dla pkt. 4.1.2 - mamcierz odwracalne ma KONKRETNE rozwiązanie

1.3 Da się obliczyć objętność objętość równoległościanu
r=np.array([[2],[0],[-8]]
g=np.array([[6],[1],[0]]
b=np.array([[1],[4],[-1]]

da się zapisać całość jako $\begin{bmatrix}
2 & 6 & 1 \\
0 & 1 & 4 \\
-8 & 0 & -1
\end{bmatrix}$

wyznacznik V = $|\det(\mathbf{A})| = 186$


4.2 ślad macierzy
Tr(A) = suma wszystkich elementów, które znajdują się na przekątnej od lewej górnej do prawej dolnej.

Wykorzystywany do optymalizacji w rachunku różniczkowym macierzy do obliczeń gradientów

4.3 rozwinięcie La placa - do ręcznego wyliczania wyznaczników

4.4 Twierdzenie Cramera
Tylko dla: liczba niewiadomych = liczba równań
Służy do wyliczania niewiadomych