Dział 4. Rozkład macierzy

In [ ]:
#funkcje z rozdziału 4.:
#forma zapisu macierzy macierz = np.array([[2, 2, 3], [4, 5, 6], [7, 8, 9]])
#     detA= np.linalg.det(macierz)   -wyznacznik
#     odwrotnaMacierz = np.linalg.inv(macierz)    -odwrócona macierz
#     ślad macierzy = np.trace(macierz))


In [17]:
import numpy as np
#ad 1. odwrotność macierzy

#zmienne
A = np.array([[4,4],[2,-4]])
B = np.array([5,1])

#funkcja:  cc = np.linalg.inv(macierz)
macierz = np.array([[2, 2, 3], [4, 5, 6], [7, 8, 9]])
print(macierz)

# Wyznacznik
detA= np.linalg.det(macierz)
print(f'Wyznacznik: {detA}')

#odwrotność
odwrotnaMacierz = np.linalg.inv(macierz)
print(odwrotnaMacierz)
#Macierz odwracalna (wyzn rozny od zera)(macierz nieosobliwa) = brak ukrytych zależności między kolumnami i wierszami

#ślad
slad = np.trace(macierz)
print(f'ślad: {slad}')





[[2 2 3]
 [4 5 6]
 [7 8 9]]
Wyznacznik: -3.0000000000000018
[[ 1.         -2.          1.        ]
 [-2.          1.          0.        ]
 [ 1.          0.66666667 -0.66666667]]
ślad: 16


In [7]:
#fundamentalne
import numpy as np

A = np.array([[4,4],[2,-4]])
B = np.array([5,1])

C = np.array([[1, 2], [3, 4]])
D = np.array([[5, 6], [7, 8]])

#Dodawanie macierzy
dodawanie= A+B
print(f'dodawanie{dodawanie}')

#Mnożenie macierzy
mnozenie = np.dot(A,B)
print(f'mnożenie{mnozenie}')

#rozwiązanie układu równań Ax=b (zadanie w pkt 2)
solution = np.linalg.solve(A,B)
print(f'wynik rozwiazania ukladu rownan{solution}')

#tranpozycja    lepiej:    X.T
transpozycja = np.transpose(A)
print(transpozycja)

#Mnożenie przez skalar - k=5 C=k*A

#macierz do potęgi
macierz_do_kwadratu = np.linalg.matrix_power(A, 2)
print(f'macierz do kwadratu{macierz_do_kwadratu}')

#macierz jednostkowa
I=np.eye(3)
print(f'macierz jednostkowa{I}')

dodawanie[[ 9  5]
 [ 7 -3]]
mnożenie[24  6]
wynik rozwiazania ukladu rownan[1.   0.25]
[[ 4  2]
 [ 4 -4]]
macierz do kwadratu[[24  0]
 [ 0 24]]
macierz jednostkowa[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


TEORIA:

4.1 Wyznacznik   
Tylko dla macierzy kwadratowych.
Co mówi wyznacznik
- Czy macierz jest odwracalna (czyli czy istnieje macierz odwrotna) 
- Czy układ równań liniowych ma jednoznaczne rozwiązanie $\text{det}(A) \neq 0$. 
- Jakie zmiany zachodzą w objętości i orientacji przestrzeni po przekształceniu liniowym.
-nieopisane Czy kolumny (lub wiersze) macierzy są liniowo niezależne.
-nieopisane Objawia stabilność układów numerycznych i analiz geometrycznych.

Ad5. W analizie numerycznej wyznacznik może mieć znaczenie przy badaniu stabilności obliczeń. Układy z wyznacznikiem bliskim zera mogą być niestabilne, ponieważ macierz jest bliska bycia osobliwą, co oznacza, że nawet małe zmiany w danych wejściowych mogą prowadzić do dużych zmian w wynikach.

4.1.1 odwrotność macierzy

$A \cdot A^{-1} = A^{-1} \cdot A = I$    
I to macierz jednostkowa, elementy na glownej przekątnej =1 

Jeżeli istnieje odwrotność, czyli $\text{det}(A) \neq 0$ 

to brak ukrytych zależności między kolumnami i wierszami.

oraz dla pkt. 4.1.2 - mamcierz odwracalne ma KONKRETNE rozwiązanie

4.1.2 Da się obliczyć objętność objętość równoległościanu
r=np.array([[2],[0],[-8]]
g=np.array([[6],[1],[0]]
b=np.array([[1],[4],[-1]]

da się zapisać całość jako $\begin{bmatrix}
2 & 6 & 1 \\
0 & 1 & 4 \\
-8 & 0 & -1
\end{bmatrix}$

wyznacznik V = $|\det(\mathbf{A})| = 186$


4.2 ślad macierzy
Tr(A) = suma wszystkich elementów, które znajdują się na przekątnej od lewej górnej do prawej dolnej.

Wykorzystywany do optymalizacji w rachunku różniczkowym macierzy do obliczeń gradientów

4.3 rozwinięcie La placa - do ręcznego wyliczania wyznaczników

4.4 Twierdzenie Cramera
Tylko dla: liczba niewiadomych = liczba równań
Służy do wyliczania niewiadomych

4.5 wielomian charakterystyczny

4.2. Wartości i wektory własne






Rozdział 2.

Algebra liniowa-nauka o wektorach i pewnych regułach ich przekształcenia. Wektory mogą być stukturami geometycznymi(strzałki)i wielomianami.

#zadanie 1. Rozwiąż układów równań
#4𝑥1 + 4𝑥2 = 5
#2𝑥1 − 4𝑥2 = 1
import numpy as np
A = np.array([[4,4],[2,-4]])
B = np.array([5,1])
solution = np.linalg.solve(A,B)
solution

>Dodawanie macierzy
C=A+B

>Mnożenie macierzy, warunek ilości kolumn i wierszy:  nxk * kxm = nxm
mnozenie = np.dot(A,B)

>macierz odwrotna-to taka, która po pomnożeniu przez macierz wyjściową daje macierz jednostkową A * A^(-1) = I

>Transpozycja macierzy-operacja polega na zamianie wierszy macierzy na kolumny i kolumny na wiersze np.transpose(A)

>Mnożenie przez skalar 



Macierz naprzemienna (antysymetryczna) - kwadratowa macierz spełnia warunek $A^T = -A
$

SymPy - biblioteka służąca do obliczeń symbolicznych
zadanie - znajdz macierz X:  2X - 3X^T =
$\begin{bmatrix}
1 & 0 \\
5 & 4
\end{bmatrix}$


In [11]:
import numpy as np
from sympy import symbols, Eq, solve

# symbole dla macierzy
a, b, c, d = symbols('a b c d')
X = np.array([[a, b], [c, d]])
XT = np.transpose(X)    #zapisywać X.T

eq_matrix = 2 * X - 3 * XT
rhs_matrix = np.array([[1, 0], [5, 4]])

#układy równań
equations = [
    Eq(eq_matrix[0, 0], rhs_matrix[0, 0]),
    Eq(eq_matrix[0, 1], rhs_matrix[0, 1]),
    Eq(eq_matrix[1, 0], rhs_matrix[1, 0]),
    Eq(eq_matrix[1, 1], rhs_matrix[1, 1])
]

solution = solve(equations, (a, b, c, d))
solution

{a: -1, b: -3, c: -2, d: -4}